# Site Settings
title: "AI Blog"
name: "AI Blog"
description: "Exploring business value through technology and strategy"
url: "https://sujoypaul.github.io"
baseurl: ""

# Author Settings
author:
  name: "Sujoy Paul"
  avatar: "/assets/images/profile.jpg"  # Optional - add your photo later
  bio: "Exploring business value through technology and strategy"
  location: "Your Location"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sujoyp@hotmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sujoyp/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sujoypaul"

# Theme Settings
theme: minimal-mistakes-jekyll

# Build Settings
markdown: kramdown
permalink: /:categories/:title/
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: /page:num/

# Table of Contents
toc:
  enabled: true
  icon: "fas fa-list-ul"
  sticky: true

# Default Front Matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      toc: true
      toc_sticky: true
      toc_label: "Table of Contents"
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true

# Footer Links
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your-email@example.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sujoypaul"

# Include these in build
include:
  - _pages

# Exclude from processing
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundler
  - .jekyll-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - readme.md
  - README.md
  - tmp